# Generated by Django 3.0.7 on 2020-07-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20200711_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='mobile',
            field=models.IntegerField(blank=True),
        ),
    ]
