# Generated by Django 3.0.7 on 2020-07-13 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_auto_20200711_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='active',
        ),
    ]
