# Generated by Django 3.0.7 on 2020-07-18 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_popup'),
    ]

    operations = [
        migrations.AddField(
            model_name='popup',
            name='priority',
            field=models.CharField(default='Urgent', max_length=100),
        ),
    ]
